---
site_name: Switcher WebAPI
site_url: https://switcher-webapi.tomfi.info
site_author: Tomer Figenblat
site_description: Switcher WebAPI Documentation

repo_url: https://github.com/TomerFi/switcher_webapi
edit_uri: ""

nav:
  - Home: index.md
  - API Endpoints:
      - All Endpoints: endpoints_all.md
      - State Endpoints: endpoints_state.md
      - Action Endpoints: endpoints_action.md
      - Config Endpoints: endpoints_config.md
      - Schedule Endpoint: endpoints_schedule.md
  - Device Types: device_types.md

markdown_extensions:
  - admonition
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: ["docs"]
  - tables
  - toc:
      permalink: ⚓︎
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  version: "2.1.0"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TomerFi
      name: TomerFi on GitHub
    - icon: fontawesome/brands/dev
      link: https://dev.to/tomerfi
      name: tomerfi on Dev.to
    - icon: fontawesome/brands/redhat
      link: https://developers.redhat.com/author/tomerfi
      name: tomerfi on Red Hat Developer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tomerfi/
      name: tomerfi on LinkedIn
  analytics:
    provider: google
    property: G-PMGFCZ93GB

plugins:
  - git-revision-date
  - search

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - content.code.annotate
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  font:
    code: Fira Code
    text: Open Sans
  palette:
    - media: "(prefers-color-scheme)"
      primary: red
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      primary: red
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
