---
name: Pages Deploy

on:
  release:
    types: [published]

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    environment: github-pages
    if: ${{ github.ref != 'refs/tags/early-access' }}
    name: Build documentation site and deploy to GH-Pages
    steps:
      - name: Source checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            requirements-dev.txt
            requirements_docs.txt

      - name: Prepare python environment
        run: |
          pip install -r requirements.txt -r requirements_docs.txt

      - name: Build documentation site
        run: mkdocs build

      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: switcher-webapi.tomfi.info
          commit_message: 'docs: deployed to gh-pages for ${{ github.ref }}'
